### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [Sora-zr/PcEnvironmentPost_app#1]
@Sora-zr 
お疲れ様です！
以下、MVPリリースレビューになります！

### 技術
Google認証や楽天APIなど、外部サービスとの連携がしっかりできている点が良いと思いました。
上記を踏まえて技術面でのFBになります。

- CRUDが中心のアプリケーションになるので、技術は使えているが機能でアピールできる部分が少し少ない印象を受けました。ガジェットごとに検索をかけられる（マウスを使っている投稿に絞る等）など、検索内容に幅を持たせてあげるような機能はいかがでしょうか？

- 技術とは少し離れてしまうのですが、GitHubを拝見させていただいたとき、issueやプルリクエストがないことが気になりました。issueやプルリクの作成は、現場では頻繁に行うことですので個人開発の段階でしっかり取り組んでおきましょう。

### ユーザビリティ

使用していて、あまり迷うところがなかったのでユーザビリティの高いアプリケーションだと思いました。
その中で、細かい点ですが以下、ユーザビリティのFBになります。

- ログイン後、Topページを表示した際ハンバーガーメニュー以外の導線がないので、次のアクションをどうすれば良いのか迷ってしまうところがありました。また何をするアプリケーションなのかもTopページの段階からはわからない状態なので、案内や使い方などをTopページに用意してあげると良さそうです。

- 投稿にある**タグのデザイン**ですが、一般的な**ボタン**のデザインと似ている印象でした。他社サービスはタグを表示する際どのようなデザインで表示しているか見比べてみても良いと思いました。

以上です！
MVPリリースとしてしっかりできていると思います！LGTMです！

また上記内容を実装するにあたり、スケジュールを立ててみてください。
スケジュール決まりましたら共有をお願いできればと思います。

また上記レビューに関して質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by Sora-zr** [comment]
お疲れさまです。

とりあえず、指摘された部分だけIssuesを作ってみました。ご確認お願いします。

あと、質問ですが、スケジュールはどこに共有すればよろしいでしょうか？

**Comment by tmtkzk0823** [comment]
> とりあえず、指摘された部分だけIssuesを作ってみました。ご確認お願いします。

こちら内容確認しました。
大丈夫だと思います。

> あと、質問ですが、スケジュールはどこに共有すればよろしいでしょうか？

こちらのコメントで共有していただければと思います。
また、追加で恐縮ですが現時点での本リリース予定の日程も共有をお願いできればと思います。

**Comment by Sora-zr** [comment]
実装スケジュールは以下の通りになります。
- タグデザイン（完了予定日：11/25）
- サービスご利用説明ページの作成（完了予定日：11/26）
- 検索機能の追加（完了予定日：11/28）

その他、上記以外で実装するものは、随時Issuesを作成し、その記事の中に完了予定日を記載します。

本リリースは12月15日までにリリースする予定です。

**Comment by tmtkzk0823** [comment]
上記確認しました！
実装頑張ってください！
